<a href="https://colab.research.google.com/github/Debayanmondal/Blue-jay-assignments/blob/main/Bluejay_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing Libraries and Dataset**

In [14]:
import pandas as pd
import numpy as np
from datetime import date


data=pd.read_excel('Assignment_Timecard (1).xlsx')
data.head(10)

,Position ID,Position Status,Time,Time Out,Timecard Hours (as Time),Pay Cycle Start Date,Pay Cycle End Date,Employee Name,File Number,Unnamed: 9,Unnamed: 10
0,WFS000054,Active,NaT,NaT,NaN,NaT,NaT,"SiWgh, PraGhjEM",54,NaN,NaN
1,WFS000065,Active,2023-09-12 10:08:00,2023-09-12 13:53:00,3:45,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
2,WFS000065,Active,2023-09-12 14:23:00,2023-09-12 19:02:00,4:39,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
3,WFS000065,Active,2023-09-13 10:08:00,2023-09-13 14:20:00,4:12,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
4,WFS000065,Active,2023-09-13 14:50:00,2023-09-13 20:44:00,5:54,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
5,WFS000065,Active,2023-09-14 10:09:00,2023-09-14 14:30:56,4:21,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
6,WFS000065,Active,2023-09-14 15:00:52,2023-09-14 19:14:00,4:14,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
7,WFS000065,Active,2023-09-15 10:11:00,2023-09-15 14:41:00,4:30,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
8,WFS000065,Active,2023-09-15 15:11:00,2023-09-15 19:05:00,3:54,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN
9,WFS000065,Active,2023-09-16 09:51:00,2023-09-16 14:50:48,4:59,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN

# **Converting the Time column to Datatime Format And Extracting the day from that**

In [15]:
data['Time'] = pd.to_datetime(data['Time'], errors='coerce')
data.info()
data['Time'].dt.day
data['date']=data['Time'].dt.day
data.iloc[1:20]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Position ID               1484 non-null   object
 1   Position Status           1484 non-null   object
 2   Time                      1474 non-null   datetime64[ns]
 3   Time Out                  1470 non-null   datetime64[ns]
 4   Timecard Hours (as Time)  1474 non-null   object
 5   Pay Cycle Start Date      1474 non-null   datetime64[ns]
 6   Pay Cycle End Date        1474 non-null   datetime64[ns]
 7   Employee Name             1484 non-null   object
 8   File Number               1484 non-null   int64
 9   Unnamed: 9                0 non-null      float64
 10  Unnamed: 10               1 non-null      object
dtypes: datetime64[ns](4), float64(1), int64(1), object(5)
memory usage: 127.7+ KB

,Position ID,Position Status,Time,Time Out,Timecard Hours (as Time),Pay Cycle Start Date,Pay Cycle End Date,Employee Name,File Number,Unnamed: 9,Unnamed: 10,date
1,WFS000065,Active,2023-09-12 10:08:00,2023-09-12 13:53:00,3:45,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,12.0
2,WFS000065,Active,2023-09-12 14:23:00,2023-09-12 19:02:00,4:39,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,12.0
3,WFS000065,Active,2023-09-13 10:08:00,2023-09-13 14:20:00,4:12,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,13.0
4,WFS000065,Active,2023-09-13 14:50:00,2023-09-13 20:44:00,5:54,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,13.0
5,WFS000065,Active,2023-09-14 10:09:00,2023-09-14 14:30:56,4:21,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,14.0
6,WFS000065,Active,2023-09-14 15:00:52,2023-09-14 19:14:00,4:14,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,14.0
7,WFS000065,Active,2023-09-15 10:11:00,2023-09-15 14:41:00,4:30,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,15.0
8,WFS000065,Active,2023-09-15 15:11:00,2023-09-15 19:05:00,3:54,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,15.0
9,WFS000065,Active,2023-09-16 09:51:00,2023-09-16 14:50:48,4:59,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,16.0
10,WFS000065,Active,2023-09-16 15:20:39,2023-09-16 20:19:00,4:59,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,16.0
11,WFS000065,Active,2023-09-19 09:55:00,2023-09-19 13:56:00,4:01,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,19.0
12,WFS000065,Active,2023-09-19 14:26:00,2023-09-19 18:29:00,4:03,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,19.0
13,WFS000065,Active,2023-09-20 09:54:00,2023-09-20 14:12:00,4:18,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,20.0
14,WFS000065,Active,2023-09-20 14:42:00,2023-09-20 18:46:00,4:04,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,20.0
15,WFS000065,Active,2023-09-21 09:55:00,2023-09-21 14:03:00,4:08,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,21.0
16,WFS000065,Active,2023-09-21 14:33:00,2023-09-21 18:47:00,4:14,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,21.0
17,WFS000065,Active,2023-09-22 09:55:00,2023-09-22 14:50:15,4:55,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,22.0
18,WFS000065,Active,2023-09-22 15:20:09,2023-09-22 20:26:00,5:06,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,22.0
19,WFS000065,Active,2023-09-23 09:55:00,2023-09-23 15:47:00,6:52,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65,NaN,NaN,23.0

# **Selecting only few columns on basis of which we are going find the result**

In [16]:
data=data[['Position ID','Employee Name','date']]
data.head()

  Position ID    Employee Name  date
0   WFS000054  SiWgh, PraGhjEM   NaN
1   WFS000065  REsaXiaWE, XAis  12.0
2   WFS000065  REsaXiaWE, XAis  12.0
3   WFS000065  REsaXiaWE, XAis  13.0
4   WFS000065  REsaXiaWE, XAis  13.0

# **Creating a new dataframe called new_df and Adding a new column in it called 'difference' to store the difference between two consecutive values in 'date' column**

In [17]:
new_df=pd.DataFrame(data)
new_df['difference']=new_df['date'].diff()
new_df['difference']=new_df['difference'].fillna(value=0)
new_df['difference']=new_df['difference'].astype(int)
new_df = new_df[new_df['difference'] != 0]

# **Defining a Function to iterate over the difference column and whenever it encounter 6 consecutive 1's(p.s  it means that particular person has worked for 7 consecutive days) it will replace the first encountered 1 with a random number(e.g. 100). Whenever this function is called it will take a column(i.e. list) as argument and it will return an updated column(i.e. list).**

In [18]:
def replace_first_1_with_100(column):
    count = 0
    for i in range(len(column)):
        if column.iloc[i] == 1:
            count += 1
            if count == 6:
                column.iloc[i-5] = 100
                break
        else:
            count = 0
    return column

# **1. Grouping the new_df on the basis of 'Employee Name' and applying the above function to the 'difference' columns of each groups individually and storing the result in a variable called grouped_ones**
#**2. Now adding the grouped_one list to the dataframe new_df as a column called 'ones'.**
#**3. Filtering all the values in 'ones' which are 100 and their corresponding 'Employee Name' and 'Position ID'.**
#**4.Printing all the 'Employee Name' and 'Position ID' who have worked for 7 consecutive days**

In [19]:
grouped_ones=new_df.groupby('Employee Name')['difference'].apply(replace_first_1_with_100)
new_df['ones']= grouped_ones
result_df = new_df[new_df['ones']== 100]
result_df=result_df[['Position ID','Employee Name']]
print("Employees who has worked for 7 consecutive days:")
print(" ")
print(result_df)

Employees who has worked for 7 consecutive days:

    Position ID         Employee Name
28    WFS000101       Sparks, KeWWeMh
496   WFS000424       SiWgh, JaspreeM
596   WFS000456      CEreira Jr, JEse
705   WFS000473  GAeWdia, JAaW CarXEs

<ipython-input-19-a33d4835e5c3>:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  grouped_ones=new_df.groupby('Employee Name')['difference'].apply(replace_first_1_with_100)